server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://111.231.85.51:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: springboot
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wyb.vue.entity
logging:
  level:
    com.wyb.vue.repository.*: debug
