server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=True
    username: root
    password: 123456
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  redis:
    host: 127.0.0.1
    port: 6379
    #    database: 0
    #    cluster:
    #      nodes:
    #        - 127.0.0.1:6380
    #        - 127.0.0.1:6381
    #        - 127.0.0.1:6382
    #        - 127.0.0.1:6480
    #        - 127.0.0.1:6481
    #        - 127.0.0.1:6482
    lettuce:
      pool:
        max-idle: 20
        max-wait:
        min-idle: 1
        max-active: 20

#  cache:
#    type: ehcache
#    ehcache:
#      config: ehcache.xml

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wyb.cache.dao.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.wyb.cache: debug


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

memcache:
  ip: 192.168.31.128
  port: 11211
